import { body } from 'express-validator';

export const settingsBodyValidator = [
  body('companyName').optional({ values: 'falsy' }).isString().trim().isLength({ min: 2, max: 120 }),
  body('email').optional({ values: 'falsy' }).isEmail().normalizeEmail(),
  body('phone').optional({ values: 'falsy' }).isString().trim(),
  body('whatsapp').optional({ values: 'null' }).isString(),
  body('address').optional({ values: 'falsy' }).isString(),
  body('facebook').optional({ values: 'null' }).isString(),
  body('instagram').optional({ values: 'null' }).isString(),
  body('linkedin').optional({ values: 'null' }).isString(),
  body('youtube').optional({ values: 'null' }).isString(),
  body('websiteDescription').optional({ values: 'falsy' }).isString(),
  body('heroHeading').optional({ values: 'falsy' }).isString(),
  body('heroSubtitle').optional({ values: 'falsy' }).isString(),
  body('aboutIntro').optional({ values: 'null' }).isString(),
  body('vision').optional({ values: 'null' }).isString(),
  body('mission').optional({ values: 'null' }).isString(),
  body('philosophy').optional({ values: 'null' }).isString(),
  body('differentiators').optional({ values: 'null' }).isString(),
  body('aboutHeadline').optional({ values: 'null' }).isString(),
  body('yearsExperience').optional({ values: 'falsy' }).isInt({ min: 0 }).toInt(),
  body('projectsCompleted').optional({ values: 'falsy' }).isInt({ min: 0 }).toInt(),
  body('clientsServed').optional({ values: 'falsy' }).isInt({ min: 0 }).toInt(),
  body('awardsWon').optional({ values: 'falsy' }).isInt({ min: 0 }).toInt(),
];
